import { Product } from '../models/index.js';

export const seedProducts = async () => {
  try {
  await Product.bulkCreate([
    { name: 'Vintage Bottle', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 2, price: 98.56, quantity:3, image_url: 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A600080443_1?fit=fit&wid=2400&hei=1800' },
    { name: 'Storied Vase', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 112.48, quantity:3, image_url: 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A600080370_1?fit=fit&wid=2400&hei=1800'},
    { name: 'Ceramic Mug Set woth Gold Details', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 130.00, quantity:3, image_url: 'https://enjoyceramicart.com/cdn/shop/files/daisymug2.webp?v=1731757322' },
    { name: 'Ceramic Mug Set - Bumble Bees', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 50.00, quantity:3, image_url: 'https://cdn.shoplightspeed.com/shops/628201/files/57890992/image.jpg' },
    { name: 'Coffee cup with hearts', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 2, price: 18.00, quantity:3, image_url: 'https://s.alicdn.com/@sc04/kf/Hde3793d4f0f844d6bfa0ae8a269d3cec9.jpg_720x720q50.jpg' },
    { name: 'Knit doll - Rabbit', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 53.49, quantity:3, image_url: 'https://i.etsystatic.com/25272875/r/il/8a2a5e/3311783399/il_1588xN.3311783399_d6dm.jpg' },
    { name: 'Owl Wizard Crochet Pattern', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 48.00, quantity:3, image_url: 'https://i.etsystatic.com/31258461/r/il/d27d06/6102209882/il_1588xN.6102209882_wdhd.jpg' },
    { name: 'Amigurimi Teddy', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 3, price: 27.99, quantity:3, image_url: 'https://i.etsystatic.com/41536180/r/il/c83762/5375513021/il_1588xN.5375513021_5hfx.jpg' },
    { name: 'Wooden Montessori Duck Toy', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 12.48, quantity:3, image_url: 'https://i.etsystatic.com/17906550/r/il/9e2471/3056336850/il_1588xN.3056336850_hc6t.jpg' },
    { name: 'Waddling Duckies', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 3, price: 50.00, quantity:3, image_url: 'https://i.etsystatic.com/33115825/r/il/bf3535/6493888742/il_1588xN.6493888742_338n.jpg' },
    { name: 'Couple Heart', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 45.00, quantity:3, image_url: 'https://i.etsystatic.com/6914574/r/il/87e7ac/626479066/il_1588xN.626479066_cmew.jpg' },
    { name: 'Valentines Heart Quilling', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 3, price: 15.00, quantity:3, image_url: 'https://i.etsystatic.com/6443268/r/il/06751c/1740389534/il_1588xN.1740389534_gpvb.jpg' },
    { name: 'Quilled Bunny', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 25.00, quantity:3, image_url: 'https://i.etsystatic.com/31876778/r/il/80a4ab/6684735167/il_1588xN.6684735167_kued.jpg' },
    { name: 'Spring Whimsical Bunny', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 10.00, quantity:3, image_url: 'https://i.etsystatic.com/28760026/r/il/a4b124/6590339304/il_1588xN.6590339304_tt28.jpg' },
    { name: 'Flower letter', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 3, price: 30.59, quantity:3, image_url: 'https://i.etsystatic.com/19841887/r/il/5badd1/3750977493/il_1588xN.3750977493_mi73.jpg' },
    { name: 'Viking Beer Tankard', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 32.45, quantity:3, image_url: 'https://i.ebayimg.com/images/g/-BYAAOSwBNNkeOI4/s-l1600.webp' },
    { name: 'Gallant Gunmetal', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 2, price: 42.10, quantity:3, image_url: 'https://www.homewetbar.com/cdn/shop/files/gallant-gunmetal-personalized-beer-mug-242569.jpg?v=1743776285&width=1000' },
    { name: 'Night shift stoneware', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 48.00, quantity:3, image_url: 'https://nightshiftstoneware.com/cdn/shop/files/IMG_3086_1024x1024.heic?v=1734638932' },
    { name: 'Smokestack', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 37.50, quantity:3, image_url: 'https://greyfoxpottery.com/wp-content/uploads/2015/04/custom-beer-steins-smokestack-2.jpg' },
    { name: 'Pottery Mug', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 2, price: 78.28, quantity:3, image_url: 'https://i.etsystatic.com/16156688/r/il/4ed8bd/5039617674/il_1588xN.5039617674_jvkb.jpg' }
  ], { individualHooks: true });
  console.log('Products seeded successfully');
}
  catch (error) {
    console.error('Error seeding products:', error);
  }
};