import { Product } from '../models/index.js';

export const seedProducts = async () => {
  try {
  await Product.bulkCreate([
    { name: 'Vintage Bottle', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 2, price: 98.56, quantity:3, image_url: 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A600080443_1?fit=fit&wid=2400&hei=1800' },
    { name: 'Storied Vase', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 112.48, quantity:3, image_url: 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A600080370_1?fit=fit&wid=2400&hei=1800'},
    { name: 'Ceramic Mug Set woth Gold Details', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 130.00, quantity:3, image_url: 'https://enjoyceramicart.com/cdn/shop/files/daisymug2.webp?v=1731757322' },
    { name: 'Ceramic Mug Set - Bumble Bees', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 3, price: 50.00, quantity:3, image_url: 'https://cdn.shoplightspeed.com/shops/628201/files/57890992/image.jpg' },
    { name: 'Coffee cup with hearts', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 1, seller_id: 2, price: 18.00, quantity:3, image_url: 'https://s.alicdn.com/@sc04/kf/Hde3793d4f0f844d6bfa0ae8a269d3cec9.jpg_720x720q50.jpg' },
    { name: 'Knit doll - Rabbit', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 53.49, quantity:3, image_url: 'https://i.etsystatic.com/25272875/r/il/8a2a5e/3311783399/il_1588xN.3311783399_d6dm.jpg' },
    { name: 'Owl Wizard Crochet Pattern', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 48.00, quantity:3, image_url: 'https://i.etsystatic.com/31258461/r/il/d27d06/6102209882/il_1588xN.6102209882_wdhd.jpg' },
    { name: 'Amigurimi Teddy', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 3, price: 27.99, quantity:3, image_url: 'https://i.etsystatic.com/41536180/r/il/c83762/5375513021/il_1588xN.5375513021_5hfx.jpg' },
    { name: 'Wooden Montessori Duck Toy', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 2, price: 12.48, quantity:3, image_url: 'https://i.etsystatic.com/17906550/r/il/9e2471/3056336850/il_1588xN.3056336850_hc6t.jpg' },
    { name: 'Waddling Duckies', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 2, seller_id: 3, price: 50.00, quantity:3, image_url: 'https://i.etsystatic.com/33115825/r/il/bf3535/6493888742/il_1588xN.6493888742_338n.jpg' },
    { name: 'Couple Heart', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 45.00, quantity:3, image_url: 'https://i.etsystatic.com/6914574/r/il/87e7ac/626479066/il_1588xN.626479066_cmew.jpg' },
    { name: 'Valentines Heart Quilling', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 3, price: 15.00, quantity:3, image_url: 'https://i.etsystatic.com/6443268/r/il/06751c/1740389534/il_1588xN.1740389534_gpvb.jpg' },
    { name: 'Quilled Bunny', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 25.00, quantity:3, image_url: 'https://i.etsystatic.com/31876778/r/il/80a4ab/6684735167/il_1588xN.6684735167_kued.jpg' },
    { name: 'Spring Whimsical Bunny', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 2, price: 10.00, quantity:3, image_url: 'https://i.etsystatic.com/28760026/r/il/a4b124/6590339304/il_1588xN.6590339304_tt28.jpg' },
    { name: 'Flower letter', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 3, seller_id: 3, price: 30.59, quantity:3, image_url: 'https://i.etsystatic.com/19841887/r/il/5badd1/3750977493/il_1588xN.3750977493_mi73.jpg' },
    { name: 'Viking Beer Tankard', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 32.45, quantity:3, image_url: 'https://i.ebayimg.com/images/g/-BYAAOSwBNNkeOI4/s-l1600.webp' },
    { name: 'Gallant Gunmetal', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 2, price: 42.10, quantity:3, image_url: 'https://www.homewetbar.com/cdn/shop/files/gallant-gunmetal-personalized-beer-mug-242569.jpg?v=1743776285&width=1000' },
    { name: 'Night shift stoneware', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 48.00, quantity:3, image_url: 'https://nightshiftstoneware.com/cdn/shop/files/IMG_3086_1024x1024.heic?v=1734638932' },
    { name: 'Smokestack', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 3, price: 37.50, quantity:3, image_url: 'https://greyfoxpottery.com/wp-content/uploads/2015/04/custom-beer-steins-smokestack-2.jpg' },
    { name: 'Pottery Mug', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu neque eget ex pulvinar fringilla. Pellentesque nisi felis, accumsan eget leo a, laoreet dignissim libero.', category_id: 4, seller_id: 2, price: 78.28, quantity:3, image_url: 'https://i.etsystatic.com/16156688/r/il/4ed8bd/5039617674/il_1588xN.5039617674_jvkb.jpg' }
  ], { individualHooks: true });
  console.log('Products seeded successfully');
}
  catch (error) {
    console.error('Error seeding products:', error);
  }
};

// export const seedProducts = async () => {
//   try {
//   await Product.bulkCreate([
//     { name: 'GameBoy', description: 'Electronic game', category_id: 1, seller_id: 2, price: 32, quantity:3, image_url: 'https://m.media-amazon.com/images/I/51K+7ftcmNL._SX522_.jpg' },
//     { name: 'smart watch', description: 'watch that keeps track of health stats', category_id: 1, seller_id: 3, price: 112.48, quantity:3, image_url: 'https://www.att.com/scmsassets/global/devices/other/google/google-pixel-watch-3-41mm/defaultimage/obsidian-hero-zoom.png' },
//     { name: 'old cell phone', description: 'slow, but it still works', category_id: 1, seller_id: 3, price: 12, quantity:3, image_url: 'https://m.media-amazon.com/images/I/61p2UI2ZPgL._SL1500_.jpg' },
//     { name: 'battery charger', description: 'charges AA and AAA batteries', category_id: 1, seller_id: 3, price: 8, quantity:3, image_url: 'https://cdn11.bigcommerce.com/s-1jdv28j2qm/images/stencil/1280x1280/products/3257/6883/1654734712.386.513__46198.1655157767.jpg?c=2' },
//     { name: 't-shirt', description: 'Clothing t shirt - Finnish for bear', category_id: 2, seller_id: 2, price: 6, quantity:3, image_url: 'https://us.karhu.com/cdn/shop/products/Photo_1_c2c9d1a3-bcb1-49fd-bf9a-79542dddf04d_1070x.jpg?v=1649252687' },
//     { name: 'skirt', description: 'Awesome skirt', category_id: 2, seller_id: 2, price: 19, quantity:3, image_url: 'https://media.kohlsimg.com/is/image/kohls/6102265_Black?wid=805&hei=805&op_sharpen=1' },
//     { name: 'OCR shoes', description: 'Shoes for obstacle course running', category_id: 2, seller_id: 2, price: 79.99, quantity:3, image_url: 'https://i.ebayimg.com/images/g/eYEAAOSwQS5nSNOB/s-l1600.webp' },
//     { name: 'funky socks', description: 'circus animals and colorful dots', category_id: 2, seller_id: 3, price: 12.48, quantity:3, image_url: 'https://m.media-amazon.com/images/I/71GltrnOEYL._AC_SX679_.jpg' },
//     { name: 'spatula', description: 'Household spatula specifically for pancakes', category_id: 3, seller_id: 2, price: 9, quantity:3, image_url: 'https://images.thdstatic.com/productImages/23021817-047a-44da-b63e-1ab531f616ae/svn/grey-kitchen-utensil-sets-985116398m-64_145.jpg' },
//     { name: 'red curtains', description: 'Curtains fit for a palace', category_id: 3, seller_id: 3, price: 11, quantity:3, image_url: 'https://s7.orientaltrading.com/is/image/OrientalTrading/VIEWER_ZOOM/red-curtain-backdrop-2-pc-~3_2329' },
//     { name: 'sofa', description: 'free of bread crumbs, may have loose change', category_id: 3, seller_id: 2, price: 410, quantity:3, image_url: 'https://assets.wfcdn.com/im/45089286/resize-h400-w400%5Ecompr-r85/2928/292865933/Chelcey+62.9%27%27+Upholstered+Sofa.jpg' },
//     { name: 'area rug', description: 'with a turtle design', category_id: 3, seller_id: 3, price: 88, quantity:3, image_url: 'https://rioxmall.com/cdn/shop/files/2_NIgBe.jpg?v=1736778850&width=800' },
//     { name: 'Onyx Storm', description: 'Books of your favorite clit lit', category_id: 4, seller_id: 2, price: 27.89, quantity:3, image_url: 'https://prodimage.images-bn.com/pimages/9781649377159_p0_v5_s1200x1200.jpg' },
//     { name: 'Gideon Bible', description: 'someone handed it over', category_id: 4, seller_id: 2, price: 0.5, quantity:3, image_url: 'https://i.ebayimg.com/images/g/ljIAAOSw3otkurP4/s-l1600.webp' },
//     { name: 'Conquest Bread', description: 'The Conquest of Bread by Peter Kropotkin, first edition', category_id: 4, seller_id: 3, price: 745.8, quantity:3, image_url: 'https://pictures.abebooks.com/isbn/9781528772426-us.jpg' },
//     { name: 'TV Guide', description: 'From March 7-13, 1992, mint condition', category_id: 4, seller_id: 3, price: 99, quantity:3, image_url: 'https://www.tvguidemagazine.com/archive/suboffer/cache/1990s/1992/9abab358f3f73a6760542724246ab8a90ba3c165.19920307_c1_620.jpg?cached=1593656933' },
//     { name: 'TMNT Don', description: 'Toy Teenage Mutant Ninja Turtle Donatello', category_id: 5, seller_id: 2, price: 48.6, quantity:3, image_url: 'https://retrotoyquest.com/wp-content/uploads/2022/07/TMNT-Card-Front-1988-Donatello-768x1005.jpg' },
//     { name: 'Rubix cube', description: 'A rubix cube that may or may not be unsolvable', category_id: 5, seller_id: 3, price: 7, quantity:3, image_url: 'https://www.spinmaster.com/static/432e11e0d6e72707df91fe7379962cdc/apaj3jqyv59uylrx7erk.jpg' },
//     { name: 'GI Joe', description: 'A Real American Hero', category_id: 5, seller_id: 3, price: 17.76, quantity:3, image_url: 'https://i5.walmartimages.com/asr/57f2f091-fb0b-4196-8ddf-d5539b402edb.2dcd6bdc69b0f2a6f0daeb27ee87ba31.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF' },
//     { name: 'toy gun', description: 'Shall not be infringed', category_id: 5, seller_id: 3, price: 2.22, quantity:3, image_url: 'https://m.media-amazon.com/images/I/71W-qrnQCjL._AC_SL1500_.jpg' },
//     { name: 'Paste sauce', description: 'Foody pasta sauce', category_id: 6, seller_id: 2, price: 1.99, quantity:3, image_url: 'https://www.kitchentreaty.com/wp-content/uploads/2012/05/magic-3-ingredient-pasta-sauce-8.jpg' },
//     { name: 'Anchovies', description: 'fresh import from Italy', category_id: 6, seller_id: 2, price: 6.54, quantity:3, image_url: 'https://i.etsystatic.com/27476817/r/il/980a19/6147825227/il_794xN.6147825227_5yo4.jpg' },
//     { name: 'Hambone', description: 'Good for boiling to make a broth', category_id: 6, seller_id: 3, price: 0.79, quantity:3, image_url: 'https://rawdogchews.com/cdn/shop/products/44031-ham-bone.jpg?v=1647442951' },
//     { name: 'panko crumbs', description: 'Which I got from my couch', category_id: 6, seller_id: 2, price: 14, quantity:3, image_url: 'https://www.thewickednoodle.com/wp-content/uploads/2023/09/panko-breadcrumbs-recipe-720x720.jpg.webp' },
//   ], { individualHooks: true });
//   console.log('Products seeded successfully');
// }
//   catch (error) {
//     console.error('Error seeding products:', error);
//   }
// };